export const notesPool = [
    "I thought the flag was nearby... I was wrong.",
    "They don't die. Not even with a sword.",
    "The fog hid the exit. I'm stuck.",
    "Every step echoes... calling someone.",
    "Do you feel it? Someone's watching you.",
    "Footprints on the floor... But I'm alone.",
    "I left a light... But it went out.",
    "He spoke to me. Right from the walls.",
    "They come when the music stops.",
    "If you found this — you're next.",
    "I didn’t move... but the map changed.",
    "The flag whispered. Don't go to it.",
    "I ran in circles. Five hours. No way out.",
    "Blood? No... Just paint. Probably.",
    "Someone's drawing maps. And they're watching.",
    "Don't raise the flag. No matter what.",
    "The zombies smile. Now I do too.",
    "He woke up when I opened the chest.",
    "This isn't a maze. It's a cage.",

    "If you're reading this, I didn’t make it.",
    "I forgot why I came here... How’s your run going?",
    "Top left corner = bad life choices.",
    "Drop the sword, grab the pickaxe. Or was it the other way? I'm lost.",
    "Chest is empty. Just like my sense of humor.",
    "I found the exit! Then I woke up.",
    "Chased the flag, found existential dread.",
    "GG EZ. I lost. Good luck, lol.",
    "Why does a zombie need a pickaxe? Nope, not asking.",
    "Notch was here. Or maybe just his shadow.",
    "Flag? I thought it was a donut.",
];